### ISSUE TITLE
Manual LicenseUrl mappings fail with packages using deprecated licenseurl

### ISSUE THREAD

**Issue by jrobertson-insite** [tomchavakis/nuget-license#107]
When using the licenseurl mapping functionality along with a package using a deprecated license url the mapping fails. At the time nuget-license does the mapping it has not run the HandleDeprecateMSFTLicense method to fix it. So the licenseurl mapping file still sees the license as 'https://aka.ms/deprecateLicenseUrl'. It is unclear to me if this is intentional or if I should make a pull request with this logic in Program.cs changed. Below are reproduction steps.

**Command**
`dotnet-project-licenses -i ./TestLicenseCheck.csproj -u -o -j --licenseurl-to-license-mappings .\mappings.json --allowed-license-types .\allowed-licenses.json`

**./TestLicenseCheck.csproj** - blank project with a single nuget reference to Iron Pdf
`<PackageReference Include="IronPdf" Version="2022.4.5575" />`

**mappings.json**
`{
    "https://ironpdf.com/docs/license/eula/": "Commercial"
}`

**allowed-licenses.json**
`[
    "Commercial"
]`

**Comment by jrobertson-insite** [comment]
After some further reflection maybe this is ok and I should change how we map manually or otherwise from commercial licenses rather than URL. Since URL just points me to https://www.nuget.org/packages/IronPdf/2022.4.5575/License after the HandleDeprecateMSFTLicense method.

**Comment by tomchavakis** [comment]
Hi @jrobertson-insite,

Thank you for bringing up this issue. I am not sure if it's ok to close this issue or not. 
Do you feel that the functionality of this feature should be changed?
Thank you

**Comment by jrobertson-insite** [comment]
Unclear. I think we've gone another route in ours and that makes sense to us. I feel like this may throw others off but if the URL turns into the nuget url with the version in the path it probably isn't going to be any more helpful.

Short answer, yes I think this should be closed.

**Comment by jbriggs22** [comment]
Hi @tomchavakis, thanks for this tool, exactly what I was looking for.

However, I am still seeing this issue... it seems that due to the `ValidateLicenses` method running prior to `HandleDeprecateMSFTLicense` this is still a problem. As I believe the `LibraryInfo.LicenseUrl` would still be  `https://aka.ms/deprecateLicenseUrl` and not a nuget url which I have in my mapping file.

I'm seeing this issue using similar Command and mappings.json file with a project referencing https://www.nuget.org/packages/ParkSquare.ConfigDump.AspNetCore/1.0.16 

Could this be re-opened?
