### ISSUE TITLE
Cannot get repository info in json output

### ISSUE THREAD

**Issue by tahakucukkatirci** [tomchavakis/nuget-license#146]
OS: MacOS Catalina 10.15.7

When I run

`dotnet dotnet-project-licenses -i <path> -u -j --outfile /tmp/nuget-licenses.json`

in the command line, it produces the json file but `Repository` key is not included in the output. When I used the tool a few days ago I was able to get that information as well. I have installed the package locally and uninstalled & reinstalled a few times. But it was the same version, i.e. `2.4.0` all the time. Don't know why this happens now. Any idea?

**Comment by tahakucukkatirci** [comment]
Ok, I figured out the bug


https://github.com/tomchavakis/nuget-license/blob/b1e35b1d024714e80ba63e4d325b86346056a889/src/Methods.cs#L445

In the body of this if condition, the repository info is not included. The reason I was able to get that information before was running without `-u` flag.

**Comment by sensslen** [comment]
The -u parameter is kind of odd. Since it explicitly specifies that there is no interest in the actual version of the nuget but rather have it only occur once in the list. Most nugets that specify their license as url tend to update the url for newer versions. Therefore it makes no sense to print any repository/license URL event if only one version is referenced. Please use the tool without the -u flag to get output with proper license URL information.

Are you OK with closing this issue with this information?

**Comment by sensslen** [comment]
Closed with above explanation
