### ISSUE TITLE
Transitive dependencies does not work as expected

### ISSUE THREAD

**Issue by svenclaesson** [tomchavakis/nuget-license#148]
I have a project with NuGet references
- FluentNHibernate 3.1.0
- NHibernate 5.3.10

FluentNHibernate 3.1.0 has a transitive dependency on version >=5.3.3 of NHibernate

First step
Run dotnet-project-licenses on a clean setup (empty nuget cache) this works as expected with output
* FluentNHibernate 3.1.0
* NHibernate 5.3.10

Second step
Update NHibernate to 5.3.13

Third step
Run dotnet-project-licenses again with output
- FluentNHibernate 3.1.0
- **NHibernate 5.3.10**
- NHibernate 5.3.13

Even if I have no reference to 5.3.10 in my project anymore

**Comment by sensslen** [comment]
I assume this issue comes from the fact that the current released version of the tool does its own dependency resolution and hence uses the lowest and highest allowed version to verify against (If I'm not mistaken). This is the main issue the current alpha version (3.0.0-alpha.#) tries to solve. Could you please try whether that version works for you? Please keep in mind that this version does not yet support all features of the original tool.

**Comment by svenclaesson** [comment]
Glad to hear it's an known issue and that its being worked on! Unfortunately I can't get 3.0.0-alpha.5 to work. 

- It wrongly assumes my solution file is in XML-format
- No way of specifying outfile/output-directory

`-t` takes a very long time with System.* and Microsoft.* namespaces, 1 minute for only on one of my project files, so I want to exclude those.
In version 2.4.0, I could do this with `--packages-filter` and a regex.
In version 3.0.0-alpha `--ignored-packages` must be exact match?

Thanks a bunch for your work!

**Comment by sensslen** [comment]
You are absolutely right. Currently the parameter --ignored-packages does only support exact matching. However implementing regex matching should be pretty straight forward. On a different note I guess that ignored packages (espacially if they are matched using regex) should occur in the output as well so that it is very clear what happens. Would you mind writing up a little api specification for that feature?

**Comment by svenclaesson** [comment]
It's good the way it works in 2.4.0 where you get an explanation when its excluded with log output `-l Verbose` only.
It should not show up in the normal output table if its excluded.

On a side note. The output table looks nice but since the column width depending on max string length it's not practical to use with git diff since it looks like every row changed. Output as csv would be one way around that or being able to set min width as an option.

**Comment by sensslen** [comment]
We just recently added a feature to print the output in json format to allow automated processing. This feature has not yet been published. Would that work for you as well?

I‘ll try to find some time to work on the exclude logic.

**Comment by svenclaesson** [comment]
JSON works fine but please make it pretty printed. I don't think that's the case in 2.4.0.

**Comment by sensslen** [comment]
For pretty printed json output I created a pull request: see #149

**Comment by tomchavakis** [comment]
Hi @sensslen,

The PR #149 looks fine by me. @svenclaesson Can you please review the PR and if you feel that it's fine we can merge it and create a new release.
Thank you !!

**Comment by tomchavakis** [comment]
Hi @sensslen, @svenclaesson, 

Thank you for the code review and for making this project much better :) 
A new version https://www.nuget.org/packages/dotnet-project-licenses/3.0.0-alpha.6 has been released.
If you feel that the implementation is fine, then I suggest that we can close the ticket.
Thank you.

**Comment by svenclaesson** [comment]
The original issue is solved by with new approach in 3.0.0-alpha#

**Comment by sensslen** [comment]
@svenclaesson as a follow up on the prerformance issue you encounter I opened a new issue - see #151
