### ISSUE TITLE
GitHub branch redirects appear to fail

### ISSUE THREAD

**Issue by AaronFeickert** [tomchavakis/nuget-license#60]
GitHub allows for branch redirects (for example, for projects that rename their default branch from `master` to `main`). The tool doesn't appear to follow these redirects, so license text fetching can fail.

I'm happy to submit a PR with a fix, if the desired behavior is that such redirects are followed by default.

**Comment by ChrisMcKee** [comment]
```csharp
new HttpClient(new HttpClientHandler
{
    AllowAutoRedirect = true,
    MaxAutomaticRedirections = 5
});
```

**Comment by tomchavakis** [comment]
Hi @AaronFeickert ,

Thank you for pointing this out.
I have updated the code to handle possible redirections. 
https://github.com/tomchavakis/nuget-license/pull/62

On the other hand, the tool retrieves the license URL from the nuget API. 

@ChrisMcKee, if you go at the following nuget page
https://www.nuget.org/packages/BCrypt.Net-Next/
you will see that the license of the project is linked with the master instead of main branch. 
As a result, the tool will present the license which is associated with nuget. 
A possible solution would be to make an extra call to the github URL and if the github redirects to main branch then update the license URL but I am not sure if this is the expected way.

**Comment by ChrisMcKee** [comment]
Yeah it's sorted in GitHub. Damn branch renaming joys

**Comment by AaronFeickert** [comment]
> Hi @AaronFeickert ,
> 
> Thank you for pointing this out.
> I have updated the code to handle possible redirections.
> #62
> 
> On the other hand, the tool retrieves the license URL from the nuget API.
> 
> @ChrisMcKee, if you go at the following nuget page
> https://www.nuget.org/packages/BCrypt.Net-Next/
> you will see that the license of the project is linked with the master instead of main branch.
> As a result, the tool will present the license which is associated with nuget.
> A possible solution would be to make an extra call to the github URL and if the github redirects to main branch then update the license URL but I am not sure if this is the expected way.

Feel free to close #61 if it is not useful for this purpose.

**Comment by AaronFeickert** [comment]
The linked pull request #62 does not appear to fix this.

**Comment by tomchavakis** [comment]
@AaronFeickert, the https://github.com/tomchavakis/nuget-license/pull/61 is working only if you use the flag export-license-texts.
Moreover, there are other cases with other licenses that instead of text the output is HTML. 
I'll try to fix it asap.

**Comment by tomchavakis** [comment]
@AaronFeickert , I'll close the related issue which resolved with this PR:
https://github.com/tomchavakis/nuget-license/pull/63
